In [1]:
# Data Ingestion
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

# Define file paths
SENTIMENT_FILE = "data/fear_greed_index.csv"
TRADES_FILE = "data/historical_data.csv"

In [2]:
# Load the datasets into pandas DataFrames
try:
    df_sentiment = pd.read_csv(SENTIMENT_FILE)
    df_trades = pd.read_csv(TRADES_FILE)
    print("Datasets loaded successfully!")
except FileNotFoundError as e:
    print(f"Error loading files: {e}. Please check your file paths.")

Datasets loaded successfully!

In [3]:
print(f"Shape: {df_sentiment.shape}")
print("-" * 40)

# Display data types and non-null counts
df_sentiment.info()

# Display the first 5 rows in a formatted table
display(df_sentiment.head())

Shape: (2644, 4)
----------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       2644 non-null   int64
 1   value           2644 non-null   int64
 2   classification  2644 non-null   str
 3   date            2644 non-null   str
dtypes: int64(2), str(2)
memory usage: 82.8 KB

    timestamp  value classification        date
0  1517463000     30           Fear  2018-02-01
1  1517549400     15   Extreme Fear  2018-02-02
2  1517635800     40           Fear  2018-02-03
3  1517722200     24   Extreme Fear  2018-02-04
4  1517808600     11   Extreme Fear  2018-02-05

In [4]:
print(f"Shape: {df_trades.shape}")
print("-" * 40)

# Display data types and non-null counts
df_trades.info()

# Display the first 5 rows in a formatted table
display(df_trades.head())

Shape: (211224, 16)
----------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211224 non-null  str
 1   Coin              211224 non-null  str
 2   Execution Price   211224 non-null  float64
 3   Size Tokens       211224 non-null  float64
 4   Size USD          211224 non-null  float64
 5   Side              211224 non-null  str
 6   Timestamp IST     211224 non-null  str
 7   Start Position    211224 non-null  float64
 8   Direction         211224 non-null  str
 9   Closed PnL        211224 non-null  float64
 10  Transaction Hash  211224 non-null  str
 11  Order ID          211224 non-null  int64
 12  Crossed           211224 non-null  bool
 13  Fee               211224 non-null  float64
 14  Trade ID          211224 non-null  float64
 15  Timestamp         211224 non-null  float64
dtypes: bool(1), float64(8), int64(1), str(6)
memory usage: 24.4 MB

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12